Repository discordutilitybot/utilitybot, pull requests merged in 2020-10, with the labels that each got.

#35 bump discord.py
  requirements.txt
Labels: dependencies, enhancement, good first issue

#37 moved /backend and /frontend to /src and deleted /static
  website/src/backend/Dockerfile
  website/src/docker.compose-development.yml
  website/src/frontend/.dockerignore
  website/src/frontend/Dockerfile
  website/src/frontend/app.py
  website/src/frontend/requirements.txt
  website/src/frontend/templates/404.html
  website/src/frontend/templates/commands.html
  website/src/frontend/templates/contact.html
  website/src/frontend/templates/css/error-style.css
  website/src/frontend/templates/css/style.css
  website/src/frontend/templates/faq.html
  website/src/frontend/templates/home.html
  website/src/frontend/templates/imgs/utilitybot.png
  website/src/frontend/templates/js/error-script.js
  website/src/frontend/templates/js/site.js
  website/src/frontend/templates/privacy.html
Labels: enhancement, good first issue, question

#40 Simple help command (REVAMP)
  cogs/help.py
Labels: enhancement

#41 Update docker.compose.yml
  website/src/docker.compose.yml
Labels: enhancement, feature

#43 Update secrets.py with more data
  secrets.py
Labels: enhancement

#44 Flask custom error pages
  website/src/backend/errors/403.html
  website/src/backend/errors/404.html
  website/src/frontend/templates/404.html
Labels: enhancement, feature

#45 Update container-info text rather than just the fillers.
  website/src/frontend/templates/home.html
Labels: enhancement, feature

#47 Create /tests for unit testing
  tests/test_bot_info.py
Labels: enhancement

#48 Create LICENSE
  LICENSE
Labels: enhancement, question
